[build]
  command = "npm run build"
  publish = "dist"
  node_version = "22.12.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "22.12.0"
  NPM_FLAGS = "--force"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = "dist"